name: 'Cache'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - run: pip install -r requirements.txt

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Get latest version'
        id: version
        run: echo "id=$(curl -s https://raw.githubusercontent.com/misode/mcmeta/summary/version.txt)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: '.cache'
          key: mcmeta-${{ steps.version.outputs.id }}
          restore-keys: |
            mcmeta-

      - run: python main.py --reset --version ${{ steps.version.outputs.id }} -e data -e assets -e summary -e registries
        env:
          github-username: misode
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: misode/mcmeta
