name: 'Run'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - run: pip install -r requirements.txt

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: '.cache'
          key: mcmeta-${{ inputs.version }}
          restore-keys: |
            mcmeta-

      - run: python main.py --version ${{ inputs.version }} --fetch --export all --commit --push
        env:
          github-username: misode
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: misode/mcmeta
